language: ruby
cache: bundler

script:
  - bundle exec rspec

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem update bundler

rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
